name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [
            { name: "windows", image: "windows-latest" },
            { name: "macos", image: "macos-latest" },
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install node modules
        run: npm ci --no-audit --no-fund --progress=false
      - name: Presubmit check (e.g. lint, format)
        # Only run on macos to avoid redundancy
        if: contains(matrix.os.name, 'macos')
        run: npm run presubmit
      - name: Type-checking
        # Only run on macos to avoid redundancy
        if: contains(matrix.os.name, 'macos')
        run: npm run ts
      - name: Unit tests
        # Only run on macos to avoid redundancy
        if: contains(matrix.os.name, 'macos')
        run: npm run test
      - name: Build application
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: npm run package
